### ISSUE TITLE
Error coming in npm start

### ISSUE THREAD

**Issue by aarkay06** [ameybhavsar24/ww-wra-goog#1]
Hi , sorry for disturbing again😅. This time I used this package and ran npm install and then npm start but getting these errors

![image](https://user-images.githubusercontent.com/88158135/128996239-1c5f3ac0-28df-44c2-a7c3-2026d0ccbfab.png)

**Comment by aarkay06** [comment]
Also this doesn't work

![image](https://user-images.githubusercontent.com/88158135/129002483-9b503e75-4a67-42d5-876d-31f1a313a915.png)

**Comment by aarkay06** [comment]
I haven't installed GIT in my pc yet...I thought its neccesary for this to work so I downloaded but I am not getting what to do

**Comment by aarkay06** [comment]
I have everything , and no error came , till Step 4
But even after installing git step 5 is not working

![image](https://user-images.githubusercontent.com/88158135/129013193-3da8af28-f68d-4859-8311-9ae59ed533bc.png)

Step 5 error

![image](https://user-images.githubusercontent.com/88158135/129013356-de93a530-accb-406a-91b0-ebc4dffcee7b.png)

And I think since its failing that's why step6 is also not working (maybe)
.
.
.
.
.
The previous package was working without these steps....Do I really need to use heroku and Git

**Comment by aarkay06** [comment]
![image](https://user-images.githubusercontent.com/88158135/129138905-af0d1757-7687-4dcd-8cdf-1e609e582cad.png)

As you can see I turned few of the lines into comments that I thought are about session storage....And then QR was succesfully showing but when i scanned , it gave an error....which is coming , most probably, due to the lines that I made into comments

Please help with it

**Comment by ameybh** [comment]
Hello @KrishnaBros2, there a bit of problem in the code. You need to create an `.env` file with the Wolfram alpha APP ID and set `WW_SESSION={}`.
Once that is done, run the app again. You should see a QR to authenticate. After successfully scanning the QR, a session string object should be printed in terminal like `{WA ... }`. 
Make sure to copy it exactly and set it to `WW_SESSION` in `.env`. Try restarting the app and now it should start without authentication.

I'll update the code in some time but you can try this until then.

**Comment by aarkay06** [comment]
But I am not getting a WA Session

**Comment by ameybh** [comment]
I'll update the code in sometime.

**Comment by aarkay06** [comment]
I added a new line of code where i will get result from this api---> https://www.boredapi.com/api/activity --- whenever someone writes !boared ...I am getting the message in the console....But It is not replying and giving this error

![image](https://user-images.githubusercontent.com/88158135/129158921-7cb5676f-ab92-499c-87e7-a750cd099e39.png)


And i have made some changes in the ww-wra package of urs....this one is ww-wra-goog.....Since that one was wroking so I decided to make changes to it but this one is also giving the same errors

**Comment by ameybh** [comment]
Hello @KrishnaBros2, I took a look at your code which I believe is at https://github.com/KrishnaBros2/WA-Bot./blob/main/index.js. 
You have not required the https module like:
https://github.com/ameybhavsar24/ww-wra-goog/blob/3cf9857561c9c6cfc5e8a253424e224a12094e5b/index.js#L4

**Comment by aarkay06** [comment]
In WA BOT 2 on my GitHub , I added this line but still not working

**Comment by aarkay06** [comment]
Edit : Yaa I saw it...I didn't add that.

Sorry for that. Let me correct it

**Comment by aarkay06** [comment]
OH MY GOD!! It's working now

Thanks A Lot

**Comment by KrishnaBros2** [comment]
You are Genius🙏🙏🤩🤩
